# ============================================================================
# ADDRESS REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-09 12:56:16 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.address import AddressUpdate, AddressCreate, AddressOut

async def create_address(address_data: AddressCreate) -> AddressOut:
    address_dict = address_data.model_dump()
    result =await db.addresss.insert_one(address_dict)
    result = await db.addresss.find_one(filter={"_id":result.inserted_id})
    returnable_result = AddressOut(**result)
    return returnable_result

async def get_address(filter_dict: dict) -> Optional[AddressOut]:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Address filter is required."
        )
    try:
        result = await db.addresss.find_one(filter_dict)

        if result is None:
            return None

        return AddressOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching address: {str(e)}"
        )
    
async def get_addresss(filter_dict: Optional[dict] = None,start=0,stop=100) -> List[AddressOut]:
    try:
        filter_dict = filter_dict or {}
        start = max(0, start or 0)
        if stop is None:
            stop = start + 100
        limit = max(0, stop - start)

        cursor = (db.addresss.find(filter_dict)
        .skip(start)
        .limit(limit)
        )
        address_list = []

        async for doc in cursor:
            address_list.append(AddressOut(**doc))

        return address_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching addresss: {str(e)}"
        )
async def update_address(filter_dict: dict, address_data: AddressUpdate) -> AddressOut:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Address filter is required."
        )
    update_doc = address_data.model_dump(exclude_none=True)
    if not update_doc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No address fields to update."
        )
    result = await db.addresss.find_one_and_update(
        filter_dict,
        {"$set": update_doc},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Address not found."
        )
    returnable_result = AddressOut(**result)
    return returnable_result

async def delete_address(filter_dict: dict):
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Address filter is required."
        )
    result = await db.addresss.delete_one(filter_dict)
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Address not found."
        )
    return result
