# ============================================================================
# CHAT REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-22 11:06:53 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.chat import ChatUpdate, ChatCreate, ChatOut

async def create_chat(chat_data: ChatCreate) -> ChatOut:
    chat_dict = chat_data.model_dump()
    result =await db.chats.insert_one(chat_dict)
    result = await db.chats.find_one(filter={"_id":result.inserted_id})
    returnable_result = ChatOut(**result)
    return returnable_result

async def get_chat(filter_dict: dict) -> Optional[ChatOut]:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Chat filter is required."
        )
    try:
        result = await db.chats.find_one(filter_dict)

        if result is None:
            return None

        return ChatOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching chat: {str(e)}"
        )
    
async def get_chats(filter_dict: Optional[dict] = None,start=0,stop=100) -> List[ChatOut]:
    try:
        filter_dict = filter_dict or {}
        start = max(0, start or 0)
        if stop is None:
            stop = start + 100
        limit = max(0, stop - start)

        cursor = (db.chats.find(filter_dict)
        .skip(start)
        .limit(limit)
        )
        chat_list = []

        async for doc in cursor:
            chat_list.append(ChatOut(**doc))

        return chat_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching chats: {str(e)}"
        )
async def update_chat(filter_dict: dict, chat_data: ChatUpdate) -> ChatOut:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Chat filter is required."
        )
    update_doc = chat_data.model_dump(exclude_none=True)
    if not update_doc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No chat fields to update."
        )
    result = await db.chats.find_one_and_update(
        filter_dict,
        {"$set": update_doc},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat not found."
        )
    returnable_result = ChatOut(**result)
    return returnable_result

async def delete_chat(filter_dict: dict):
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Chat filter is required."
        )
    result = await db.chats.delete_one(filter_dict)
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat not found."
        )
    return result
