# ============================================================================
# CHAT REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-22 11:06:53 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.chat import ChatUpdate, ChatCreate, ChatOut

async def create_chat(chat_data: ChatCreate) -> ChatOut:
    chat_dict = chat_data.model_dump()
    result =await db.chats.insert_one(chat_dict)
    result = await db.chats.find_one(filter={"_id":result.inserted_id})
    returnable_result = ChatOut(**result)
    return returnable_result

async def get_chat(filter_dict: dict) -> Optional[ChatOut]:
    try:
        result = await db.chats.find_one(filter_dict)

        if result is None:
            return None

        return ChatOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching chat: {str(e)}"
        )
    
async def get_chats(filter_dict: dict = {},start=0,stop=100) -> List[ChatOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.chats.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        chat_list = []

        async for doc in cursor:
            chat_list.append(ChatOut(**doc))

        return chat_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching chats: {str(e)}"
        )
async def update_chat(filter_dict: dict, chat_data: ChatUpdate) -> ChatOut:
    result = await db.chats.find_one_and_update(
        filter_dict,
        {"$set": chat_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = ChatOut(**result)
    return returnable_result

async def delete_chat(filter_dict: dict):
    return await db.chats.delete_one(filter_dict)