# ============================================================================
# DRIVER REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-03 10:19:25 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.driver import DriverUpdate, DriverCreate, DriverOut

async def create_driver(driver_data: DriverCreate) -> DriverOut:
    driver_dict = driver_data.model_dump()
    result =await db.drivers.insert_one(driver_dict)
    result = await db.drivers.find_one(filter={"_id":result.inserted_id})
    returnable_result = DriverOut(**result)
    return returnable_result

async def get_driver(filter_dict: dict) -> Optional[DriverOut]:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Driver filter is required."
        )
    try:
        result = await db.drivers.find_one(filter_dict)

        if result is None:
            return None

        return DriverOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching driver: {str(e)}"
        )
    
async def get_drivers(filter_dict: Optional[dict] = None,start=0,stop=100) -> List[DriverOut]:
    try:
        filter_dict = filter_dict or {}
        start = max(0, start or 0)
        if stop is None:
            stop = start + 100
        limit = max(0, stop - start)

        cursor = (db.drivers.find(filter_dict)
        .skip(start)
        .limit(limit)
        )
        driver_list = []

        async for doc in cursor:
            driver_list.append(DriverOut(**doc))

        return driver_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching drivers: {str(e)}"
        )
async def update_driver(filter_dict: dict, driver_data: DriverUpdate) -> DriverOut:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Driver filter is required."
        )
    update_doc = driver_data.model_dump(exclude_none=True)
    if not update_doc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No driver fields to update."
        )
    result = await db.drivers.find_one_and_update(
        filter_dict,
        {"$set": update_doc},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Driver not found."
        )
    returnable_result = DriverOut(**result)
    return returnable_result

async def delete_driver(filter_dict: dict):
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Driver filter is required."
        )
    result = await db.drivers.delete_one(filter_dict)
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Driver not found."
        )
    return result
