# ============================================================================
# PAYMENT REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-15 02:47:18 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.payment import PaymentUpdate, PaymentCreate, PaymentOut

async def create_payment(payment_data: PaymentCreate) -> PaymentOut:
    payment_dict = payment_data.model_dump()
    result =await db.payments.insert_one(payment_dict)
    result = await db.payments.find_one(filter={"_id":result.inserted_id})
    returnable_result = PaymentOut(**result)
    return returnable_result

async def get_payment(filter_dict: dict) -> Optional[PaymentOut]:
    try:
        result = await db.payments.find_one(filter_dict)

        if result is None:
            return None

        return PaymentOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching payment: {str(e)}"
        )
    
async def get_payments(filter_dict: dict = {},start=0,stop=100) -> List[PaymentOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.payments.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        payment_list = []

        async for doc in cursor:
            payment_list.append(PaymentOut(**doc))

        return payment_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching payments: {str(e)}"
        )
async def update_payment(filter_dict: dict, payment_data: PaymentUpdate) -> PaymentOut:
    result = await db.payments.find_one_and_update(
        filter_dict,
        {"$set": payment_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = PaymentOut(**result)
    return returnable_result

async def delete_payment(filter_dict: dict):
    return await db.payments.delete_one(filter_dict)