# ============================================================================
# PAYOUT REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-21 02:16:23 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.payout import PayoutUpdate, PayoutCreate, PayoutOut

async def create_payout(payout_data: PayoutCreate) -> PayoutOut:
    payout_dict = payout_data.model_dump()
    result =await db.payouts.insert_one(payout_dict)
    result = await db.payouts.find_one(filter={"_id":result.inserted_id})
    returnable_result = PayoutOut(**result)
    return returnable_result

async def get_payout(filter_dict: dict) -> Optional[PayoutOut]:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Payout filter is required."
        )
    try:
        result = await db.payouts.find_one(filter_dict)

        if result is None:
            return None

        return PayoutOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching payout: {str(e)}"
        )
    
async def get_payouts(filter_dict: Optional[dict] = None,start=0,stop=100) -> List[PayoutOut]:
    try:
        filter_dict = filter_dict or {}
        start = max(0, start or 0)
        if stop is None:
            stop = start + 100
        limit = max(0, stop - start)

        cursor = (db.payouts.find(filter_dict)
        .skip(start)
        .limit(limit)
        )
        payout_list = []

        async for doc in cursor:
            payout_list.append(PayoutOut(**doc))

        return payout_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching payouts: {str(e)}"
        )
async def update_payout(filter_dict: dict, payout_data: PayoutUpdate) -> PayoutOut:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Payout filter is required."
        )
    update_doc = payout_data.model_dump(exclude_none=True)
    if not update_doc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No payout fields to update."
        )
    result = await db.payouts.find_one_and_update(
        filter_dict,
        {"$set": update_doc},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Payout not found."
        )
    returnable_result = PayoutOut(**result)
    return returnable_result

async def delete_payout(filter_dict: dict):
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Payout filter is required."
        )
    result = await db.payouts.delete_one(filter_dict)
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Payout not found."
        )
    return result
