# ============================================================================
# PAYOUT REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-21 02:16:23 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.payout import PayoutUpdate, PayoutCreate, PayoutOut

async def create_payout(payout_data: PayoutCreate) -> PayoutOut:
    payout_dict = payout_data.model_dump()
    result =await db.payouts.insert_one(payout_dict)
    result = await db.payouts.find_one(filter={"_id":result.inserted_id})
    returnable_result = PayoutOut(**result)
    return returnable_result

async def get_payout(filter_dict: dict) -> Optional[PayoutOut]:
    try:
        result = await db.payouts.find_one(filter_dict)

        if result is None:
            return None

        return PayoutOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching payout: {str(e)}"
        )
    
async def get_payouts(filter_dict: dict = {},start=0,stop=100) -> List[PayoutOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.payouts.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        payout_list = []

        async for doc in cursor:
            payout_list.append(PayoutOut(**doc))

        return payout_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching payouts: {str(e)}"
        )
async def update_payout(filter_dict: dict, payout_data: PayoutUpdate) -> PayoutOut:
    result = await db.payouts.find_one_and_update(
        filter_dict,
        {"$set": payout_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = PayoutOut(**result)
    return returnable_result

async def delete_payout(filter_dict: dict):
    return await db.payouts.delete_one(filter_dict)