# ============================================================================
# RIDE REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-09 17:57:12 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import Any, Dict, List, Optional
from schemas.ride import RideUpdate, RideCreate, RideOut
from services.place_service import get_place_details




async def _hydrate_place_from_place_id(
    place_value: object,
    cache: Dict[str, object],
) -> object:
    if not isinstance(place_value, str):
        return place_value
    place_id = place_value.strip()
    if not place_id:
        return place_value

    cached_value = cache.get(place_id)
    if cached_value is not None:
        return cached_value

    hydrated_value: object = place_value
    try:
        place_response = await get_place_details(place_id=place_id)
        place_data = getattr(place_response, "data", None) or {}
        lat = place_data.get("lat")
        lng = place_data.get("lng")
        if lat is not None and lng is not None:
            hydrated_value = {
                "place_id": place_id,
                "name": place_data.get("name") or place_data.get("address") or place_id,
                "formatted_address": place_data.get("address") or place_data.get("name") or place_id,
                "longitude": float(lng),
                "latitude": float(lat),
            }
    except Exception:
        hydrated_value = place_value

    cache[place_id] = hydrated_value
    return hydrated_value


async def _hydrate_ride_places(doc: Dict[str, Any], cache: Dict[str, object]) -> Dict[str, Any]:
    hydrated_doc = dict(doc)
    hydrated_doc["pickup"] = await _hydrate_place_from_place_id(hydrated_doc.get("pickup"), cache)
    hydrated_doc["destination"] = await _hydrate_place_from_place_id(hydrated_doc.get("destination"), cache)
    return hydrated_doc


async def check_if_user_has_an_existing_active_ride(user_id:str):
    active_statuses = [
        "scheduled",
        "matching",
        "findingDriver",
        "arrivingToPickup",
        "drivingToDestination",
        "awaitingPayment",
        "paymentFailed",
        "pendingPayment",
    ]
    existing_ride = await db.rides.find_one({
        "userId": user_id, 
        "rideStatus": {"$in": active_statuses}
    })
    if existing_ride:
        raise HTTPException(
            status_code=400, 
            detail=f"You still have an active ride ({existing_ride['rideStatus']}). Please complete or cancel it first."
        )



async def create_ride(ride_data: RideCreate) -> RideOut:
    ride_dict = ride_data.model_dump()

    result =await db.rides.insert_one(ride_dict)
    result = await db.rides.find_one(filter={"_id":result.inserted_id})
    hydrated_result = await _hydrate_ride_places(result, {})
    returnable_result = RideOut(**hydrated_result)
    return returnable_result

async def get_ride(filter_dict: dict) -> Optional[RideOut]:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Ride filter is required."
        )
    try:
        result = await db.rides.find_one(filter_dict)

        if result is None:
            return None

        hydrated_result = await _hydrate_ride_places(result, {})
        return RideOut(**hydrated_result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching ride: {str(e)}"
        )
    
async def get_rides(filter_dict: Optional[dict] = None,start=0,stop=100) -> List[RideOut]:
    try:
        filter_dict = filter_dict or {}
        start = max(0, start or 0)
        if stop is None:
            stop = start + 100
        limit = max(0, stop - start)

        cursor = (db.rides.find(filter_dict)
        .skip(start)
        .limit(limit)
        )
        ride_list = []
        place_cache: Dict[str, object] = {}

        async for doc in cursor:
            hydrated_doc = await _hydrate_ride_places(doc, place_cache)
            ride_list.append(RideOut(**hydrated_doc))

        return ride_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching rides: {str(e)}"
        )
async def update_ride(filter_dict: dict, ride_data: RideUpdate) -> RideOut:
    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Ride filter is required."
        )
    update_doc = ride_data.model_dump(exclude_none=True)
    if not update_doc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No ride fields to update."
        )
    result = await db.rides.find_one_and_update(
        filter_dict,
        {"$set": update_doc},
        return_document=ReturnDocument.AFTER
    )
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Ride not found."
        )
    hydrated_result = await _hydrate_ride_places(result, {})
    returnable_result = RideOut(**hydrated_result)
    return returnable_result

async def delete_ride(filter_dict: dict):
    from bson import ObjectId
    from bson.errors import InvalidId

    if not filter_dict:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Ride filter is required."
        )

    if "_id" in filter_dict and isinstance(filter_dict["_id"], str):
        try:
            
            filter_dict["_id"] = ObjectId(filter_dict["_id"])
        except InvalidId:
            
            pass 

    result = await db.rides.delete_one(filter_dict)
    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Ride not found."
        )
    return result
