# ============================================================================
# STRIPE_EVENT REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-12-14 23:24:46 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.stripe_event import StripeEventUpdate, StripeEventCreate, StripeEventOut
from pymongo.errors import DuplicateKeyError

async def create_stripe_event(stripe_event_data: StripeEventCreate) -> StripeEventOut:
    stripe_event_dict = stripe_event_data.model_dump()

    try:
        result = await db.stripe_events.insert_one(stripe_event_dict)
    except DuplicateKeyError:
        raise ValueError("Stripe event with this stripe_id already exists")

    result = await db.stripe_events.find_one(
        {"_id": result.inserted_id}
    )

    return StripeEventOut(**result)

async def get_stripe_event(filter_dict: dict) -> Optional[StripeEventOut]:
    try:
        result = await db.stripe_events.find_one(filter_dict)

        if result is None:
            return None

        return StripeEventOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching stripe_event: {str(e)}"
        )
    
async def get_stripe_events(filter_dict: dict = {},start=0,stop=100) -> List[StripeEventOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.stripe_events.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        stripe_event_list = []

        async for doc in cursor:
            stripe_event_list.append(StripeEventOut(**doc))

        return stripe_event_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching stripe_events: {str(e)}"
        )
async def update_stripe_event(filter_dict: dict, stripe_event_data: StripeEventUpdate) -> StripeEventOut:
    result = await db.stripe_events.find_one_and_update(
        filter_dict,
        {"$set": stripe_event_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = StripeEventOut(**result)
    return returnable_result

async def delete_stripe_event(filter_dict: dict):
    return await db.stripe_events.delete_one(filter_dict)